// <auto-generated />
using System;
using BitacoraApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitacoraApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190804042318_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BitacoraApp.API.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Direccion");

                    b.Property<DateTime>("FechaEntrega");

                    b.Property<DateTime>("FechaIngreso");

                    b.Property<string>("NombreCliente");

                    b.Property<string>("NombreEquipo");

                    b.Property<string>("Observacione");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Bitacoras");
                });
#pragma warning restore 612, 618
        }
    }
}
