// <auto-generated />
using System;
using BitacoraApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitacoraApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190817052314_ope")]
    partial class ope
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BitacoraApp.API.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Direccion");

                    b.Property<DateTime>("FechaEntrega");

                    b.Property<DateTime>("FechaIngreso");

                    b.Property<string>("NombreCliente");

                    b.Property<string>("NombreEquipo");

                    b.Property<string>("Observacione");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("BitacoraApp.API.Models.Divicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num1");

                    b.Property<int>("Num2");

                    b.Property<string>("operacion");

                    b.Property<double>("resultado");

                    b.HasKey("Id");

                    b.ToTable("Divicions");
                });

            modelBuilder.Entity("BitacoraApp.API.Models.Exponencial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num1");

                    b.Property<int>("Num2");

                    b.Property<string>("operacion");

                    b.Property<double>("resultado");

                    b.HasKey("Id");

                    b.ToTable("Exponencials");
                });

            modelBuilder.Entity("BitacoraApp.API.Models.Multi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num1");

                    b.Property<int>("Num2");

                    b.Property<string>("operacion");

                    b.Property<double>("resultado");

                    b.HasKey("Id");

                    b.ToTable("Multis");
                });

            modelBuilder.Entity("BitacoraApp.API.Models.Raiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num1");

                    b.Property<int>("Num2");

                    b.Property<string>("operacion");

                    b.Property<double>("resultado");

                    b.HasKey("Id");

                    b.ToTable("Raiz_");
                });

            modelBuilder.Entity("BitacoraApp.API.Models.Resta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num1");

                    b.Property<int>("Num2");

                    b.Property<string>("operacion");

                    b.Property<double>("resultado");

                    b.HasKey("Id");

                    b.ToTable("Restas");
                });

            modelBuilder.Entity("BitacoraApp.API.Models.Suma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Num1");

                    b.Property<int>("Num2");

                    b.Property<string>("operacion");

                    b.Property<double>("resultado");

                    b.HasKey("Id");

                    b.ToTable("Sumas");
                });
#pragma warning restore 612, 618
        }
    }
}
